### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by cazitouni** [qwc-services/qwc-legend-service#20]
Hello,

I allow myself to contact you because there is something I do not understand about the configuration of the legend service.
For example, If I want to use a custom legend for my layer quartier in my theme quartiers what am I supose to do ? 

![image](https://github.com/qwc-services/qwc-legend-service/assets/92778930/1ddfd894-45be-414f-a96f-6bac07563fe6)

I've tried multiple things, adding a quartier.png in the legends folder, adding a subfolder quartiers/quartier.png and even copying the ressources part into tenantconfig.json then adding legend_image param. But so far nothing worked. 

I use docker and the folder seems corectly mounted. 
![image](https://github.com/qwc-services/qwc-legend-service/assets/92778930/709feed9-1af9-4bc2-8770-bc3905fdabb0)

Also if I write directly "legend_image": "quartier.png" in legendconfig.json it'll work, but get erased everytime i refresh the configs.

Could you help me a bit with that ? 

Thanks in advance,
Kind regards, Clément.

**Comment by manisandro** [comment]
The approaches for custom legend images are described here [1], do these work for you?

[1] https://qwc-services.github.io/topics/LegendGraphics/

**Comment by cazitouni** [comment]
@manisandro, 
Thanks for the answer, yes this is what I've tried for, I even tried to copy ressources part from featurelegendconfig.json into tenantconfig then adding the parameter legend_image but it does not work either.

My tenantconfig legend part look like this 

![image](https://github.com/qwc-services/qwc-legend-service/assets/92778930/86ae04a6-a25d-433b-bbfa-ab1e0b3c61ee)
And my folder structure like this
![image](https://github.com/qwc-services/qwc-legend-service/assets/92778930/b1677315-2ef8-4379-88d5-0d373f76b6cb)

But legendconfig still gets no params : 

![image](https://github.com/qwc-services/qwc-legend-service/assets/92778930/3c35f101-abee-4efc-b847-9a3e6efcf09b)

**Comment by cazitouni** [comment]
My bad, It do actually work with the folder quartiers/quartier.png.
I got confused by the fact that the parameter isn't written in config, but the legend show the correct pictures. 

Thanks again for the quick answer.
